version: '2'
services:
  hub:
    image: selenium/hub
    ports:
      - 4444:4444
  node_firefox:
    image: selenium/node-firefox
    ports:
      - 5900
    links:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
  node_chrome:
    image: selenium/node-chrome
    ports:
      - 5900
    links:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
  test:
    build: .
    links:
      - hub
